# DEVELOPMENT!!!!!!
version: "3.9"
services:
  api:
    stdin_open: true
    hostname: apod-trav-api
    build: ./
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis-server:6379
    volumes:
      - ./:/usr/src/app
    ports:
      - 8005:3000
    depends_on:
      - redis-server

  redis-server:
    image: redis
    ports:
      - "8379:6379"
    restart: always
    volumes:
      - ./redis-data:/var/lib/redis

networks:
  default:
    external: true
    name: fun_network
